**Step-1: Import Package**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

**Step-2: Create a data frame using list**

In [3]:
names=['Ramesh','Suresh','Satish']
#pd.DataFrame(data,index,col)
pd.DataFrame(names)

0
0  Ramesh
1  Suresh
2  Satish

**Step-3-4:i want to change the index and col**

In [4]:
names=['Ramesh','Suresh','Satish']
ids=['A','B','C']
col=['Name']
pd.DataFrame(names,ids,col)

Name
A  Ramesh
B  Suresh
C  Satish

**Step-5: Data and Col**

In [5]:
names=['Ramesh','Suresh','Satish']
col=['Names']
pd.DataFrame(names,columns=col)

Names
0  Ramesh
1  Suresh
2  Satish

**Step-6: Multiple column**

In [6]:
names=['Ramesh','Suresh','Satish']
age=[20,21,23]
col=['Name','Age']
df=pd.DataFrame(zip(names,age),columns=col)
df

Name  Age
0  Ramesh   20
1  Suresh   21
2  Satish   23

**Step-7: Add a new column to already existed df**

- in above first we have taken data

- then created a df

- now we want to add new data based on requirement

In [7]:
city =['UP','Hyd','Blr']
df['city']=city
df

Name  Age city
0  Ramesh   20   UP
1  Suresh   21  Hyd
2  Satish   23  Blr

In [8]:

df['Marks']=[80,69,98]
df

Name  Age city  Marks
0  Ramesh   20   UP     80
1  Suresh   21  Hyd     69
2  Satish   23  Blr     98

**Step-8: Update the column with new values**

In [9]:
df

Name  Age city  Marks
0  Ramesh   20   UP     80
1  Suresh   21  Hyd     69
2  Satish   23  Blr     98

In [10]:
df['Marks']=[200,400,340]

In [11]:
df

Name  Age city  Marks
0  Ramesh   20   UP    200
1  Suresh   21  Hyd    400
2  Satish   23  Blr    340

**Step-9: Create empty dataframe and add the col**

In [12]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [13]:
df['Names']=['Ramesh','Suresh','Satish']
df['Age']=[20,21,23]
df

Names  Age
0  Ramesh   20
1  Suresh   21
2  Satish   23

**Step-10: Create a df using dic**

In [14]:
d={'Names':['Ramesh','Suresh','Satish'],
    'Age':[20,21,22],
  'City':['Hyd','Blr','Pune']}
df= pd.DataFrame(d)
df

Names  Age  City
0  Ramesh   20   Hyd
1  Suresh   21   Blr
2  Satish   22  Pune

In [15]:
d={'Name':'Ramesh',
   'Age':20,
   'City':'Hyd'}
pd.DataFrame(d)

ValueError: If using all scalar values, you must pass an index

In [ ]:
d={'Name':'Ramesh',
   'Age':20,
   'City':'Hyd'}
pd.DataFrame(d,index=[0])

**Step-11: Save the dataframe**

In [ ]:
# file handling session
# directory//filename.ext
# filename.ext
# we are saving df
# .csv or .xlsx

In [ ]:
df.to_csv('data.csv')

In [ ]:
df.to_csv('.csv')

In [ ]:
df.to_excel('data.xlsx')

**Step-12: Read the df**

In [ ]:
# in order to read the data
# filename.ext
# open(mobox-short.txt).read()
# open(dummy.txt,mode='w').write('hello')

# data.csv      data.xlsx
pd.read_csv('data.csv')

In [ ]:
df

In [ ]:
pd.read_excel('data.xlsx')

In [ ]:
d={'Names':['Ramesh','Suresh','Satish'],
    'Age':[20,21,22],
  'City':['Hyd','Blr','Pune']}
df= pd.DataFrame(d)
df

In [ ]:
df.to_csv
pd.read_csv

df.to_excel
pd.read_excel

In [ ]:
df.to_csv('data1.csv', index=False)

In [ ]:
pd.read_csv('data1.csv')

In [ ]:
#add one more column marks to df
df['marks']=[100,200,300]
df

**Step-13: Drop the column**

- labels

- axis
    
- index
    
- columns
    
- level
    
- inplace


In [ ]:
# if i want to drop a index
# i need to use index argument name
df.drop(columns='marks')

In [ ]:
df.drop(index=2)

In [ ]:
df.drop(columns=['City','marks'])

In [16]:
df

Names  Age  City
0  Ramesh   20   Hyd
1  Suresh   21   Blr
2  Satish   22  Pune

In [17]:
df.drop(index=1)
df.drop(columns='marks')
#===================================
df.drop('marks')Z   # if i dont give argu lable 
df.drop(1)          # 1 become lable
#===================================
# we need to axis
# axis=0 indicates index

SyntaxError: invalid syntax (2249764914.py, line 4)

In [18]:
df.drop('marks')

KeyError: "['marks'] not found in axis"

In [ ]:
df.drop('marks',axis=0)

In [ ]:
df.drop('marks',axis=1)

In [ ]:
df.drop(2)

In [ ]:
df.drop(2,axis=0)

In [ ]:
df

**Inplace**

- when we do the operation the result output is not overwriting

- means the original df is same as it is

- in order to do this we need use **inplace**

- by default inplace = False

- Make inplace = True if you want overwrite the result

In [19]:
df.drop('marks',axis=1,inplace=True)

KeyError: "['marks'] not found in axis"

In [ ]:
df

**Step-14: Rename the column**

In [20]:
d={'City':'city'   
} #{old:new}
df.rename(d,axis=1,inplace=True)

In [21]:
df

Names  Age  city
0  Ramesh   20   Hyd
1  Suresh   21   Blr
2  Satish   22  Pune

In [22]:
d1={'Age':'age'}
df.rename(d1,axis=1,inplace=True)

In [23]:
df

Names  age  city
0  Ramesh   20   Hyd
1  Suresh   21   Blr
2  Satish   22  Pune

In [24]:
d2={'Names':'name'}
df.rename(d2,axis=1,inplace=True)

In [25]:
df

name  age  city
0  Ramesh   20   Hyd
1  Suresh   21   Blr
2  Satish   22  Pune

In [26]:
d3={0:1}
df.rename(d3,axis=0,inplace=True)
df

name  age  city
1  Ramesh   20   Hyd
1  Suresh   21   Blr
2  Satish   22  Pune

In [27]:
d3={1:2}
df.rename(d3,axis=0,inplace=True)
df

name  age  city
2  Ramesh   20   Hyd
2  Suresh   21   Blr
2  Satish   22  Pune

In [28]:
## Create one more df
# x=1 to 10
# y= squ x
# x= cube x
x=list(range(1,11))
y=[i*i for i in x]
z=[i**3 for i in x ]
df=pd.DataFrame(zip(x,y,z),columns=['X','Y',
                                'Z'])
df

X    Y     Z
0   1    1     1
1   2    4     8
2   3    9    27
3   4   16    64
4   5   25   125
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

- len

- shape : df.shape

- size : df.size

- head : df.head

- tail : df.tail

- isnull : df.isnull

- dtypes : df.types

- info : df.info

In [29]:
len(df)

10

In [30]:
df.shape    # 10 rows and 3 cols

(10, 3)

In [31]:
df.size

30

In [32]:
df.head()

X   Y    Z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125

In [33]:
df.tail()

X    Y     Z
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

In [34]:
df.isnull()

X      Y      Z
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False
6  False  False  False
7  False  False  False
8  False  False  False
9  False  False  False

In [35]:
df.isnull().sum()

X    0
Y    0
Z    0
dtype: int64

In [36]:
df.dtypes

X    int64
Y    int64
Z    int64
dtype: object

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X       10 non-null     int64
 1   Y       10 non-null     int64
 2   Z       10 non-null     int64
dtypes: int64(3)
memory usage: 372.0 bytes


**Step-15: Select a columns**

In [38]:
df.columns

Index(['X', 'Y', 'Z'], dtype='object')

In [39]:
df['Z']    #no  col name here (selecting one particular col)

0       1
1       8
2      27
3      64
4     125
5     216
6     343
7     512
8     729
9    1000
Name: Z, dtype: int64

In [40]:
df['X']

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: X, dtype: int64

In [41]:
df['Y']

0      1
1      4
2      9
3     16
4     25
5     36
6     49
7     64
8     81
9    100
Name: Y, dtype: int64

In [42]:
df['Z'].values

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [43]:
df[['Y','Z']]

Y     Z
0    1     1
1    4     8
2    9    27
3   16    64
4   25   125
5   36   216
6   49   343
7   64   512
8   81   729
9  100  1000

In [44]:
df[['X','Y','Z']]

X    Y     Z
0   1    1     1
1   2    4     8
2   3    9    27
3   4   16    64
4   5   25   125
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

In [45]:
df['Z'].values.tolist()

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [46]:
df[['X','Y','Z']].values

array([[   1,    1,    1],
       [   2,    4,    8],
       [   3,    9,   27],
       [   4,   16,   64],
       [   5,   25,  125],
       [   6,   36,  216],
       [   7,   49,  343],
       [   8,   64,  512],
       [   9,   81,  729],
       [  10,  100, 1000]])

In [47]:
df[['X','Y','Z']].values.tolist()

[[1, 1, 1],
 [2, 4, 8],
 [3, 9, 27],
 [4, 16, 64],
 [5, 25, 125],
 [6, 36, 216],
 [7, 49, 343],
 [8, 64, 512],
 [9, 81, 729],
 [10, 100, 1000]]

In [48]:
type(df['X'])

# 1d
#series means one sqr bracket one dim

pandas.core.series.Series

In [49]:
type(df[['X','Y']])
#2d
#dataframe means 2 dim

pandas.core.frame.DataFrame

In [50]:
df['X'].shape

(10,)

In [51]:
df[['X','Y']].shape

(10, 2)

In [53]:
df   # dataframe
df['X']   #selecting one particular column
df['X'].values    #extracting the data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
df[['X','Y']]

X    Y
0   1    1
1   2    4
2   3    9
3   4   16
4   5   25
5   6   36
6   7   49
7   8   64
8   9   81
9  10  100

In [56]:
df['Z']

Z
0     1
1     8
2    27
3    64
4   125
5   216
6   343
7   512
8   729
9  1000

In [57]:
df['Z'].values

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [58]:
df['Z'].values.tolist()

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]